server:
  port: 8082

spring:
  application:
    name: issuer-ms

  datasource:
    url: jdbc:h2:mem:issuerdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  sql:
    init:
      platform: h2
  devtools:
    add-properties: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#  instance:
#    hostname: localhost

