server:
  port: 9192

spring:

  main:
    web-application-type: reactive

  application:
    name: register-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

