server:
  port: 9193

spring:
  application:
    name: oauth2-server

#  datasource:
#    url: jdbc:h2:mem:customerdb
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#
#    h2:
#      console:
#        enabled: true
#
#
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
#      defer-datasource-initialization: false
#      hibernate:
#        ddl-auto: none
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true
#      open-in-view: true
#
#    sql:
#      init:
#        platform: h2
#    devtools:
#      add-properties: true